steps:
- name: node
  entrypoint: npm
  dir: 'rcf-app'
  args: ['install']
- name: node
  entrypoint: npm
  dir: 'rcf-app'
  args: ['run', 'build']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
  dir: 'rcf-app'
timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY
